on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: run1
      run: |
        docker run jcansdale/docker-update@sha256:97ca80d69af299c49bdc2a0d6382ee826127b8a5e3f64d23822d0a2d36ff560a
    - name: run2
      run: |
        docker run jcansdale/docker-update@sha256:dc2f28dd8f886c5be0872bc63b9360d5069f35a392fac0b0aaae95c715af9733
    - name: run3
      run: |
        docker run jcansdale/docker-update@sha256:7fc4fda1d3772dfdbfc7b54bc7d3ea6f8a7ac6caf3fac79894e22a6a5ffca1df
